apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "fider.fullname" . }}
spec:
  host: {{ .Values.host.prefix }}.{{ .Values.host.clusterDomain }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ include "fider.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: 'True'
      type: Admitted
    host: {{ .Values.host.prefix }}.{{ .Values.host.clusterDomain }}
    routerName: router
    wildcardPolicy: None
