airflow:
  airflow:
    image:
      repository: docker-registry.default.svc:5000/wksv3k-tools/cas-airflow
      tag: '0.1.0-pre.023'
    config:
      AIRFLOW__CORE__REMOTE_LOGGING: True
      AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: s3:://cas-minio-wksv3k-dev.pathfinder.gov.bc.ca/minio/airflow-logs/
      AIRFLOW__CORE__LOG_CONN_ID: minio
      AIRFLOW__CORE__ENCRYPT_S3_LOGS: False
    extraVolumeMounts:
      - name: cas-airflow-home
        mountPath: /usr/local/airflow
    extraVolumes:
      - name: cas-airflow-home
        persistentVolumeClaim:
          claimName: cas-airflow-home
    extraEnv:
      - name: AIRFLOW__CORE__FERNET_KEY
        valueFrom:
          secretKeyRef:
            name: cas-airflow
            key: fernet_key
      - name: C_FORCE_ROOT
        value: 'true'
  postgresql:
    enabled: true
    postgresDatabase: postgres
  redis:
    enabled: true
    image:
      registry: registry.redhat.io
      repository: rhscl/redis-5-rhel7
      tag: 5-18.1575996553
    securityContext:
      enabled: false
    master:
      command: []
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
