airflow:
  airflow:
    image:
      repository: docker-registry.default.svc:5000/wksv3k-tools/cas-airflow
      tag: '0.1.0-pre.014'
    extraVolumeMounts:
      - name: cas-airflow-home
        mountPath: /usr/local/airflow
    extraVolumes:
      - name: cas-airflow-home
        persistentVolumeClaim:
          claimName: cas-airflow-home
    extraEnv:
      - name: C_FORCE_ROOT
        value: 'true'
      - name: AIRFLOW_CORE_REMOTE_LOGGING
        value: 'true'
      - name: AIRFLOW_ELASTICSEARCH_HOST
        value: 'airflow'
      - name: AIRFLOW_ELASTICSEARCH_LOG_ID_TEMPLATE
        value: '{{dag_id}}-{{task_id}}-{{execution_date}}-{{try_number}}'
      - name: AIRFLOW_ELASTICSEARCH_END_OF_LOG_MARK
        value: 'end_of_log'
      - name: AIRFLOW_ELASTICSEARCH_WRITE_STDOUT
        value: 'true'
  postgresql:
    enabled: true
    postgresDatabase: postgres
  redis:
    enabled: true
    image:
      registry: registry.redhat.io
      repository: rhscl/redis-5-rhel7
      tag: 5-18.1575996553
    securityContext:
      enabled: false
    master:
      command: []
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false

